#!/bin/bash

version() {
    case $1 in
        edge )
            echo "$(./publish released edge)"
            ;;

        stable )
            echo "$(./publish released stable)"
            ;;

        * )
            echo `node -e 'console.log(require("./package.json").version)'`
            ;;
    esac
}

debug() {
    mkdir -p src/lang/locals

    cp ../lang/builds/* src/lang/locals/
    cp ../lang/countries.json src/lang/

    ./node_modules/.bin/vue-cli-service electron:serve
}

case $1 in
    version )
        shift

        version $@
        ;;

    lint )
        make lint
        ;;

    debug )
        debug
        ;;

    build )
        shift

        if [[ "$OSTYPE" == "darwin"* ]]; then
            printf "\033[0;36mXcode certificates\033[0m\n"
            security unlock-keychain login.keychain

            (cd ../ && ./project pull) > /dev/null 2>&1
            (cd ../ && ./project build localization)

            printf "\033[0;36mBuild desktop\033[0m\n"
            make desktop
        fi

        ;;

    publish )
        shift

        gh auth login
        ./publish $@
        ;;

    clean )
        make clean
        ;;
esac
