#!/bin/bash

version() {
    echo `node -e 'console.log(require("./package.json").version)'`
}

case $1 in
    version )
        shift

        version $@
        ;;

    lint )
        make lint
        ;;

    debug )
        ./node_modules/.bin/vue-cli-service electron:serve
        ;;

    build )
        shift

        if [[ "$OSTYPE" == "darwin"* ]]; then
            security unlock-keychain $@ login.keychain
            (cd ../ && ./project pull) > /dev/null 2>&1
            (cd ../ && ./project build localization)
            make desktop
        fi

        ;;

    clean )
        make clean
        ;;
esac
